root: ./
structure:
  readme: README.md
  summary: SUMMARY.md
redirects:
  nd4j/backend: config/backends/README.md
  quickstart: getting-started/README.md
  contribute: getting-started/contribute.md
  android/faq: multi-project/explanation/deprecation.md
  android/first-steps: multi-project/explanation/deprecation.md
  android/image-classification: multi-project/explanation/deprecation.md
  android/linear-classifier: multi-project/explanation/deprecation.md
  android/press: multi-project/explanation/deprecation.md
  android/setup: multi-project/explanation/deprecation.md
  android/support: multi-project/explanation/deprecation.md
  android/why-deep-learning: multi-project/explanation/deprecation.md
  arbiter/layer-spaces: multi-project/explanation/deprecation.md
  arbiter/overview: multi-project/explanation/deprecation.md
  arbiter/parameter-spaces: multi-project/explanation/deprecation.md
  config/backends/config-cudnn: multi-project/explanation/config/backends/config-cudnn.md
  config/backends/cpu: multi-project/explanation/config/backends/cpu.md
  config/backends/performance-issues: multi-project/explanation/config/backends/performance-issues.md
  config/config-memory: multi-project/explanation/config/config-memory.md
  config/config-/config-workspaces: multi-project/explanation/config/config-memory/config-workspaces.md
  config/buildtools: multi-project/explanation/config/buildtools.md
  config/config-snapshots: multi-project/explanation/config/config-snapshots.md
  config/maven: multi-project/explanation/config/maven.md
  datavec/analysis: datavec/explanation/analysis.md
  datavec/conditions: datavec/explanation/conditions.md
  datavec/executors: datavec/explanation/executors.md
  datavec/filters: datavec/explanation/filters.md
  datavec/normalization: datavec/explanation/normalization.md
  datavec/operations: datavec/explanation/operations.md
  datavec/readers: datavec/explanation/readers.md
  datavec/records: datavec/explanation/records.md
  datavec/reductions: datavec/explanation/reductions.md
  datavec/schema: datavec/explanation/schema.md
  datavec/serialization: datavec/explanation/serialization.md
  datavec/transforms: datavec/explanation/transforms.md
  datavec/visualization: datavec/explanation/visualization.md
  distributed-deep-learning/apiref: spark/explanation/apiref.md
  distributed-deep-learning/data-howto: spark/how-to-guides/data-howto.md
  distributed-deep-learning/howto: spark/how-to-guides/howto.md
  distributed-deep-learning/intro: spark/tutorials/intro.md
  distributed-deep-learning/parameter-server: spark/reference/parameter-server.md
  distributed-deep-pearning/technicalref: spark/reference/technicalref.md
  getting-started/contribute: multi-project/how-to-guides/contribute.md
  getting-started/contribute/eclipse-contributors: multi-project/how-to-guides/contribute/eclipse-contributors.md
  getting-started/about: multi-project/explanation/about.md
  getting-started/beginners: multi-project/how-to-guides/beginners.md
  getting-started/benchmark: multi-project/how-to-guides/benchmark.md
  getting-started/build-from-source: multi-project/how-to-guides/build-from-source.md
  getting-started/cheat-sheet: multi-project/explanation/cheat-sheet.md
  getting-started/core-concepts: multi-project/explanation/core-concepts.md
  getting-started/examples-tour: multi-project/reference/examples-tour.md
  getting-started/quickstart:  multi-project/tutorials/quickstart.md
  getting-started/release-notes: multi-project/reference/release-notes.md
  getting-started/tutorials/advanced-autoencoder: multi-project/explanation/deprecation.md
  getting-started/tutorials/basic-autoencoder: multi-project/explanation/deprecation.md
  getting-started/tutorials/built-in-data-iterators: multi-project/explanation/deprecation.md
  getting-started/tutorials/clinicial-time-series-lstm: multi-project/explanation/deprecation.md
  getting-started/tutorials/cloud-detection-example: multi-project/explanation/deprecation.md
  getting-started/tutorials/convolutional-networks: multi-project/explanation/deprecation.md
  getting-started/tutorials/early-stopping: multi-project/explanation/deprecation.md
  getting-started/tutorials/feed-forward-networks: multi-project/explanation/deprecation.md
  getting-started/tutorials/hyperparameter-optimization: multi-project/explanation/deprecation.md
  getting-started/tutorials/instacart-multi-task-example: multi-project/explanation/deprecation.md
  getting-started/tutorials/instacart-single-task-example: multi-project/explanation/deprecation.md
  getting-started/tutorials/layers-and-preprocessors: multi-project/explanation/deprecation.md
  getting-started/tutorials/logistic-regression: multi-project/explanation/deprecation.md
  getting-started/tutorials/multilayernetwork-and-computationgraph: multi-project/explanation/deprecation.md
  getting-started/tutorials/quickstart-with-mnist: multi-project/explanation/deprecation.md
  getting-started/tutorials/recurrent-networks: multi-project/explanation/deprecation.md
  getting-started/tutorials/sea-teamperature-convolutional-lstm-example-2: multi-project/explanation/deprecation.md
  getting-started/tutorials/sea-temperature-convolutional-lstm: multi-project/explanation/deprecation.md
  getting-started/tutorials/using-multiple-gpus: multi-project/explanation/deprecation.md
  keras-import: deeplearning4j/explanation/keras-import.md
  model-zoo: deeplearning4j/explanation/model-zoo.md
  nd4j/basics: nd4j/how-to-guides/basics.md
  nd4j/elementwise: nd4j-how-to-guides/elementwise.md
  nd4j/matrix-manipulation: nd4j/how-to-guides/matrix-manipulation.md
  nd4j/overview: nd4j/explanation/overview.md
  nd4j/quickstart: nd4j/tutorials/quickstart.md
  nd4j/tensor: nd4j/reference/tensor.md
  nd4j/syntax: nd4j/reference/syntax.md
  nd4j/operation-namespaces: samediff/reference/operation-namespaces.md
  samediff/adding-ops: samediff/how-to-guides/adding-ops.md
  samediff/importing-tensorflow: samediff/how-to-guides/importing-tensorflow.md
  samediff/ops: samediff/explanation/ops.md
  samediff/variables: samediff/explanation/variables.md
  tuning-and-training: deeplearning4j/how-to-guides/tuning-and-training.md







